all:
	make --no-print-directory -f ovl_always
	make --no-print-directory -f ovl_implication
	make --no-print-directory -f ovl_increment
	make --no-print-directory -f ovl_window
	

clean:
	  rm -fr a.out *.log *.vcd tee

help:
	make --no-print-directory -f ovl_always help
	make --no-print-directory -f ovl_implication  help
	make --no-print-directory -f ovl_increment  help
	make --no-print-directory -f ovl_window  help
	
